### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by VishnuSanal** [BreadGenie/mado#10]
great work, here're some things I noticed whilst using Mado.

- not requesting camera & microphone permission on brave (v1.44.112 (Oct 12th, 2022))
	- do not display camera preview (both on home screen & on meeting screen)(PFA)
	- works fine if I give permission manually
	- works fine on firefox

![permission](https://user-images.githubusercontent.com/50027064/196035691-17d8748b-11bf-495f-8ee8-32fe5466e8b2.png)

- provision to copy link from the meeting screen

- um... a new user joined during a meeting is not shown. nor the new user can see the previous existing user.

- UI feedback when 'copy link' is clicked on the home screen

- distorted BG when not on fullscreen - PFA

![split](https://user-images.githubusercontent.com/50027064/196035698-8fc0b141-47f4-445a-9755-0ef4540bffd9.png)

**Comment by BreadGenie** [comment]
> * not requesting camera & microphone permission on brave (v1.44.112 (Oct 12th, 2022))
>       
>   * do not display camera preview (both on home screen & on meeting screen)(PFA)
>   * works fine if I give permission manually
>   * works fine on firefox

I think this is related to #2. I have noticed that some browsers aren't able to access the input devices for some reason (Not Mado exclusive. Check the results section at this [mdn page](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/devicechange_event) and you might be able to see the error.

> provision to copy link from the meeting screen

resolved ee6af0ce8059d507c989b4eb1b089a04108d6c94
>um... a new user joined during a meeting is not shown. 

resolved a29e8ab4835387df481888962fad168f4c0a714c
> nor the new user can see the previous existing user.

I'll file a separate issue for this one, since I think this would need a bit more reworking.
>  UI feedback when 'copy link' is clicked on the home screen

resolved 5e70b4de688c21b67ed29654f47da2d7a690f9fc
> distorted BG when not on fullscreen - PFA

resolved 6ec17639da3d18a3b73d2eb5c00368edd5e385e4

**Comment by BreadGenie** [comment]
Also curious why the logo isn't displayed on your machine when it does on mine (brave browser).

**Comment by VishnuSanal** [comment]
awesome!

> Also curious why the logo isn't displayed on your machine when it does on mine (brave browser).

oh, it must be some font issue on my device. I use Arch, BTW. 🙈 

since all issues mentioned here are either fixed/moved, I'm closing this issue as completed.

**Comment by BreadGenie** [comment]
Another reason the cam feed didn't appear could be that the cam feed is already  requested/used by another browser
